Gemfile
Gemfile.lock
config/initializers/devise.rb
config/locales/devise.en.yml

adding devise gems and config files

---

app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/initializers/devise.rb
config/routes.rb
db/migrate/20230531141307_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

Worked on devise, migrated table and set up User model. Installed access to devise views. Put simple forms in container to make more readable. Tested user model in rails c.
I have NOT worked on the navbar/devise view pages yet.

Work on devise

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb

adding authentication to controller

---

app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

adding turbo to the devise views and fixing the forms

---

app/models/planet.rb
db/migrate/20230531192503_create_planets.rb
db/schema.rb
test/models/planet_test.rb

Created planet model with attributes 
name, as a string
address, as a string
description, as a text
price_per_night, as an integer
number_of_guests, as an integer
completed db:migrate
tested model in rails c
added one instance of planet : "Titan"

created planet model with attributes

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_planetindex.scss
app/controllers/planets_controller.rb
app/views/pages/home.html.erb
app/views/planets/index.html.erb
app/views/planets/show.html.erb
config/routes.rb

sorted login page - my own error!
adjusted routes using resources, have **NOT** nested them inside user routes as I don't believe this is what we need.
added more content and styling to home, index (/planets) and show (/planets/:id) pages.

Building index

---

app/views/planets/index.html.erb
app/views/planets/show.html.erb

Make sure to do rails db:migrate to get the new instance of planet model

fixed the view, added an instance of planet

---

Gemfile.lock
app/controllers/bookings_controller.rb
app/controllers/planets_controller.rb
app/models/booking.rb
app/views/planets/show.html.erb
config/routes.rb
db/migrate/20230603103410_create_bookings.rb
test/controllers/bookings_controller_test.rb
test/models/booking_test.rb

As a user I can book a planet ✅
✅Page redirects to itself because there is no "booking-overview" screen yet , where I can see all my bookings.
What I did: 
* Cre ated a booking model with start_date & end_date
* Created a bookings controller
❗️ALSO:
I changed the booking form to a simple form to prevent wrong date format entries - also because the TA told me to do it ;)
❗️NO VALIDATION ADDED YET
* Missing: Date Checker 
* Missing: Check for availability to prevent double-bookings

Added booking model

---

app/views/planets/new.html.erb
db/schema.rb

The new page had a booking form which made no logical sense. centred the form too

Planet view

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/controllers/planets_controller.rb
app/policies/application_policy.rb
app/policies/planet_policy.rb
app/views/planets/new.html.erb
app/views/shared/_navbar.html.erb
test/policies/planet_policy_test.rb

Pundit add auth

---

Gemfile
Gemfile.lock
app/controllers/planets_controller.rb
app/models/planet.rb
app/views/pages/home.html.erb
app/views/planets/_form.html.erb
app/views/planets/index.html.erb
app/views/planets/new.html.erb
app/views/planets/show.html.erb
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20230604201920_create_active_storage_tables.active_storage.rb
db/schema.rb

users uploading planets' photos is ok
static background photo seems ok on home page and listing but turns grey when moving further through the website. The links are the same in all views though. I shall ask the teachers tomorrow if you dont know why.

Cloudinary

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/bookings_controller.rb
app/controllers/planets_controller.rb
app/policies/booking_policy.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/shared/_navbar.html.erb

Reverts samarman/airbnb-project-rails#36

Revert "Revert "added scope for my bookings""

---

app/assets/stylesheets/pages/_booking_index
app/views/bookings/index.html.erb

Changed delete button looks better now

changed delete button

---

app/views/bookings/index.html.erb
config/routes.rb

added the delete functionality

---

app/controllers/planets_controller.rb
app/models/planet.rb
app/policies/application_policy.rb
app/policies/planet_policy.rb
app/views/planets/edit.html.erb
app/views/planets/show.html.erb
config/routes.rb

Added edit and delete routes, actions and views where needed.
Added buttons
updated pundit to allow delete and edit only for user who created instance.

Edit delete planet

---

Gemfile
Gemfile.lock
app/controllers/planets_controller.rb
app/models/planet.rb
app/views/planets/index.html.erb

Added the search function index

added the search function to index

---

app/controllers/planets_controller.rb
app/controllers/reviews_controller.rb
app/models/planet.rb
app/models/review.rb
app/policies/review_policy.rb
app/views/planets/show.html.erb
config/routes.rb
db/migrate/20230613112722_create_reviews.rb
db/schema.rb
test/controllers/reviews_controller_test.rb
test/models/review_test.rb
test/policies/review_policy_test.rb

Gen Review Model with associations with both user and planet. User and planet have many reviews, review belongs to user and planet
Gen review controller and defined routes embedded in planet page
gen pundit policy and authorisation to create review
coded review create action and debugged.
added some basic input on planet show page so we can see the list of reviews
added simple form to create review embedded on planet show page

Build review

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/pages/_show.scss
app/views/planets/show.html.erb

just a bit of rough styling for reviews being displayed, tried a few bits that didn't work

added some styling

---

app/models/booking.rb

I have added code to booking.rb to prevent double bookings.
The method is working BUT - I had - and still have problems displaying error messages.
The last lines of other_booking_overlap are a mess. Can someone have a look at it ? Pretty please :)

Prevented double bookings for a planet with overlapping dates

---

app/assets/stylesheets/components/_card.scss
app/views/layouts/application.html.erb
app/views/planets/show.html.erb

the css seems ok and no error loading the page but computer does not interpret the number of stars crossed as the right number, says 0 for all

css to reviews and bookings

---

app/assets/stylesheets/pages/_show.scss
app/views/planets/show.html.erb

Tidied up CSS, changed form so it now stores ratings and displays the correct number of stars in the show, still need work on the radio buttons

Debug rating
